### ISSUE TITLE
ATR Artery Codes outside of Toronto still exist

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_volumes#12]
Artery Codes that represent ATRs which commence or terminate at the City of Toronto boundary are still being picked up by the assignment process. Examples include 6493, 6542 and 37244.

**Comment by aharpalaniTO** [comment]
@sunnyqywang when you get a chance, could you take a look at this?

**Comment by sunnyqywang** [comment]
do we have a toronto boundary shapefile?

**Comment by sunnyqywang** [comment]
![image](https://cloud.githubusercontent.com/assets/10987986/24154163/c8371b90-0e26-11e7-8802-9fcbe182d8c4.png)

Toronto bounday file does not match up exactly with centreline file.

**Comment by sunnyqywang** [comment]
Aside from cases like this all arterycodes outside of toronto should be flagged already.

**Comment by aharpalaniTO** [comment]
Some corner cases might still exist, but @sunnyqywang confirms that text-based checks are currently in place to eliminate counts north of steeles / west of etobicoke creek.
