### ISSUE TITLE
Compare profile data from SCOOT to FLOW

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_volumes#21]

**Comment by aharpalaniTO** [comment]
@sunnyqywang mind adding a comment here with some links to your existing work? Thanks!

**Comment by sunnyqywang** [comment]
The notebooks are stored in https://github.com/CityofToronto/bdit_data-sources/tree/master/SCOOT

**Comment by aharpalaniTO** [comment]
@sunnyqywang to revise Don Mills analysis to only show direct 3-day comparisons between SCOOT and FLOW

**Comment by sunnyqywang** [comment]
Changing the arterial corridor under investigation to Bloor; there is no complete day overlap in counts between SCOOT and FLOW on Don Mills Rd.

**Comment by sunnyqywang** [comment]
Notebooks exploring this issues are now under /bdit_volumes/descriptive analysis

**Comment by aharpalaniTO** [comment]
Add a comment in notebook explaining Point-by-point colour variation related to months @sunnyqywang
