### ISSUE TITLE
Develop data collection plan to verify SCOOT data

### ISSUE THREAD

**Issue by jwrcoleman** [CityofToronto/bdit_volumes#29]
Identify locations to deploy video counts / ATRs to further validate SCOOT data.

**Comment by jwrcoleman** [comment]
I will send an email to Trevor with count locations (lat, long) for one-day counts (lane by lane, 20s).

**Comment by aharpalaniTO** [comment]
I've sent email to Trevor to get one-day counts for these locations. Expected to come back early-mid May.
