### ISSUE TITLE
Store MTO Compass Data in Postgres

### ISSUE THREAD

**Issue by jwrcoleman** [CityofToronto/bdit_volumes#30]
Figure out the following:

1. Whether we will use raw XML data or aggregated ONE-ITS data
2. What are the issues with the data / how are gaps interpolated?
3. Process for downloading and storing the data in Postgres

**Comment by aharpalaniTO** [comment]
@aharpalani to follow up with UofT this week.

**Comment by aharpalaniTO** [comment]
@aharpalaniTO to get access to ONE-ITS next week.

**Comment by aharpalaniTO** [comment]
Closing and being supplanted by #46
