### ISSUE TITLE
Create indicators to evaluate fit of volume profiles to clusters

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_volumes#41]
Standardized metrics for external reporting... do standard indicators exist for clusters?

**Comment by sunnyqywang** [comment]
Issue addressed in commit https://github.com/CityofToronto/bdit_volumes/commit/ee2e4177e84feab827179b940b7c08420bb006f5

**Comment by aharpalaniTO** [comment]
@sunnyqywang has addressed this here: [clustering/Evaluation_fit.md](https://github.com/CityofToronto/bdit_volumes/blob/master/volume_project/clustering/Evaluation_fit.md#distribution)

**Comment by aharpalaniTO** [comment]
Looks good. Can you spell out the formula at the beginning of [the workbook](https://github.com/CityofToronto/bdit_volumes/blob/master/volume_project/clustering/Evaluation_fit.md#distribution)?

I believe the metric is something approximating:
Normalized Cluster Distance = SUM(abs(actual vol - cluster vol))/(number of points)

After that, I'll move this to closed.
