### ISSUE TITLE
Spatial Extrapolation

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_volumes#43]
Develop method for estimating volumes on segments where no data exists based on volume profiles of nearby segments. Approach will likely consist of two parts:

Collectors and above: some form of linear regression or Kriging to estimate hourly volumes based on surrounding segments

Local: Simplified approach using basic model TBD.

**Comment by aharpalaniTO** [comment]
@sunnyqywang continues to work on this.

**Comment by sunnyqywang** [comment]
[documentation and code here](https://github.com/CityofToronto/bdit_volumes/blob/master/volume_project/spatial_extrapolation/README.md)
