### ISSUE TITLE
Compare Traffic Counts to SCOOT Data

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_volumes#45]
Compare traffic data derived from video counts to raw SCOOT cycle counts

**Comment by aharpalaniTO** [comment]
1. Load raw SCOOT data into RDS
2. Load 20s count data into RDS
3. Compare SCOOT data to count data

**Comment by sunnyqywang** [comment]
Notebook comparing video counts and scoot : [notebook](https://github.com/CityofToronto/bdit_volumes/blob/master/scoot/Disaggregate_Data_Validation_SCOOT_VideoCounts.ipynb)

Notebook comparing scoot with rescu loops: [notebook](https://github.com/CityofToronto/bdit_volumes/blob/master/scoot/Disaggregate%20Data%20Validation.ipynb)

Notebook exploring fitting correction curves to scoot. [notebook](https://github.com/CityofToronto/bdit_volumes/blob/master/scoot/Disaggregate_Aggregate_SCOOT_Compare_Fit.ipynb)

**Comment by aharpalaniTO** [comment]
Thanks @sunnyqywang. Sending some comments on Slack.

**Comment by aharpalaniTO** [comment]
Also, can you add a "total" column to the evaluation fit summary table [here](https://github.com/CityofToronto/bdit_volumes/blob/master/volume_project/clustering/Evaluation_fit.md#distance-distribution-by-cluster)
