### ISSUE TITLE
Remove ramps

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_volumes#51]

**Comment by q-schen** [comment]
So it turns out the tightly placed values occurring at ramp locations aren't actually Ramp volumes, but volumes of very short Major and Minor Arterial road segments.

**Comment by radumas** [comment]
Should these be incorporated into the adjacent grouped segments? Are their volumes distinct from the adjacent segments?

**Comment by q-schen** [comment]
Current solution is to suppress labelling of features that are smaller than 10mm (in regards to scale). May revisit this later.

**Comment by jwrcoleman** [comment]
This is no longer an issue, so i'm closing it
