### ISSUE TITLE
Remove Gardiner volumes from main map

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_volumes#52]

**Comment by q-schen** [comment]
Assessed the SQL query pulling the volume data layer, does not identify arteries by streetname (e.g. F G Gardiner) and cannot isolate for Gardiner.

Considering joining up (l2 -> group_name -> centreline_id) to grab streetname to filter.

**Comment by q-schen** [comment]
Using new linear_name_full field and fcode_desc, Gardiner volumes have been removed from the main map as well as the downtown inset.

Removed one erroneous data point (l2_group number = 40917) from Gardiner inset as well.
