### ISSUE TITLE
Sidebar v 0.1 mockup

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_volumes#59]

**Comment by rcyyu** [comment]
# Map with Sidebar
![Sidebar](https://user-images.githubusercontent.com/16738516/31015954-aa04c13e-a4f0-11e7-86ad-672a68bc4378.PNG)
This mockup is the same as the sidebar I presented last week. The only difference is that the data portion of the sidebar now allows the options of downloading the data of the selected street, a link that opens a new tab to more info on the street (has the same info as the sidebar right now), and a table that contains the raw hourly values. I might combine the first tab (which contains the streetname, fname, and geo_id) with the data tab later.
# Map with Dashboard
![Dash](https://user-images.githubusercontent.com/16738516/31016089-4cfe18c2-a4f1-11e7-99bd-58abc6c32cb1.PNG)
This mockup presents the same information as the sidebar. The data is instead presented at the bottom of the page and the sidebar removed. I believe this format is more flexible and allows more information to be presented to the user as there is no need to manage the sidebar.

Both of these aren't the final design as I haven't taken that much time on CSS.
