### ISSUE TITLE
Make sure graph works on Chrome and Firefox

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_volumes#62]

**Comment by rcyyu** [comment]
As of current, the graphs work correctly on Chrome and Firefox. IE ran into problems where it doesn't support some of the operations I've been using so I can't check if Plotly works until I find an alternative for these operations. However, Plotly should be [supported](https://community.plot.ly/t/what-versions-of-ie-are-supported/1631) on IE9
