### ISSUE TITLE
Extract volumes for 2022

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_volumes#80]
- [ ] Miovision ATR data to the centreline
- [ ] ATR counts from MOVE to the centreline
- [ ] Vehicle Detector Stations (to the centreline)

We can create a new folder `volume_project/extract/2022` and put the `.sql` files in there.

**Comment by radumas** [comment]
Someone should drop what the input to TEPS should look like for future reference

**Comment by scann0n** [comment]
RE: TEPS input looked like this for Miovision:
![image](https://github.com/CityofToronto/bdit_volumes/assets/94873142/ae9fa343-c82e-4ce8-b5b0-c821bd27c356)

But it looked like this for RESCU:
![image](https://github.com/CityofToronto/bdit_volumes/assets/94873142/3bdf4bd5-56b5-47dd-970c-c3fa66819aa6)

Some observations and questions:
- Last time we sent them the Miovision anomalous ranges table; if we're going to do that we should include the intersection_uid in the output so they can join easily - do you concur?
- Should the RESCU + ATR data be formatted to match the TEPS input?

**Comment by radumas** [comment]
>    Last time we sent them the Miovision anomalous ranges table; if we're going to do that we should include the intersection_uid in the output so they can join easily - do you concur?

I think we should include the AR in the output, so that they can filter things that are questionable or whatever out without having to join. @gabrielwol might have some ideas/existing views that would help.

>    Should the RESCU + ATR data be formatted to match the TEPS input?

* ATR: Yes. I'm assuming all the speed-volume ATRs will have a speed_class. I think you should watch out for pitfalls with the other count types because they also use speed_class to code data, I think that's just classification counts? And those could use `vehicle_class` instead?
* RESCU: @gabrielwol we are not producing a 15-min speed-vol aggregate at the moment correct?

**Comment by scann0n** [comment]
There are 23 distinct arterycode + centreline_id combos with no geo_id in the gis.centreline_20220705 table, but since arterycodes are directional, this only works out to about 13 locations (as in, I count like 13 dots on this map):
![image](https://github.com/CityofToronto/bdit_volumes/assets/94873142/f52497d1-15d1-4c50-a369-332ed708fce3)

Should I just find them manually?

**Comment by gabrielwol** [comment]
> I think we should include the AR in the output, so that they can filter things that are questionable or whatever out without having to join. @gabrielwol might have some ideas/existing views that would help.

For `VIEW miovision_api.volumes_daily` I took the approach of excluding anomalous_ranges labelled as do-not-use/questionable, but including the notes for other anomalous_ranges such as "valid-caveat" in an extra column. You can see that approach in the view's sql!

>  RESCU: @gabrielwol we are not producing a 15-min speed-vol aggregate at the moment correct?

Check out `vds.veh_speeds_15min`!

**Comment by radumas** [comment]
> There are 23 distinct arterycode + centreline_id combos with no geo_id in the gis.centreline_20220705 table, but since arterycodes are directional, this only works out to about 13 locations (as in, I count like 13 dots on this map): ![image](https://private-user-images.githubusercontent.com/94873142/313754268-f52497d1-15d1-4c50-a369-332ed708fce3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTM2NDMsIm5iZiI6MTcxMDc5MzM0MywicGF0aCI6Ii85NDg3MzE0Mi8zMTM3NTQyNjgtZjUyNDk3ZDEtMTVkMS00YzUwLWEzNjktMzMyZWQ3MDhmY2UzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDIwMjIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMzhmOWM3ZWQ4ZGVjNDgwMmRmMTZkZTU2NzcwYjgwMzk4N2RjYzQ5ZThmNWY4ODg4YjNjNjc3ZGE0NDZkZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kayMeugt7HH9DgZY7NlZYO7zyRutWJTc0JNTCGlk5XA)
> 
> Should I just find them manually?

That's less than 2% of the locations so.... would be inclined to say it's not worth it.

**Comment by scann0n** [comment]
> Check out vds.veh_speeds_15min!

I did!!! Super cool to have all of this extra data!!!
I noticed there are three count tables on `vds`:
- veh_speeds_15min - has data for RESCU Detectors and Smartmicro Sensors
- veh_length_15min - has data for RESCU Detectors and Smartmicro Sensors
- counts_15min - has data for RESCU Detectors, Blue City AI and Smartmicro Sensors

Should we send data from all three tables or will veh_speeds_15min suffice? I remember hearing that "lengths" might not be particularly reliable, but maybe that's changed.

Should we send data from non-RESCU detectors?

> For VIEW miovision_api.volumes_daily I took the approach of excluding anomalous_ranges labelled as do-not-use/questionable, but including the notes for other anomalous_ranges such as "valid-caveat" in an extra column. You can see that approach in the view's sql!

Should we take the same approach? I don't have permission to see the `create script` on the view but I'll look for it on `bdit_data-sources`.

**Comment by scann0n** [comment]
Oh also, any quick ideas on how to match `vds` to the centreline?

**Comment by radumas** [comment]
>Should we send data from all three tables or will `veh_speeds_15min` suffice? Should we send data from non-RESCU detectors?

I think this `veh_speeds_15min` suffices. If the Smartmicro are on highways then I would say yes, otherwise maybe not.

>Should we take the same approach? I don't have permission to see the create script on the view but I'll look for it on bdit_data-sources.
It doesn't show in the SQL tab?

>Oh also, any quick ideas on how to match vds to the centreline?

Spatial join on [`vds_identity_locations`](https://github.com/CityofToronto/bdit_data-sources/tree/master/volumes/vds#vdsentity_locations), you could maybe run the `heading_degrees` through the logic to create `dir_bin` but I haven't investigated. Otherwise have to identify direction of travel some other way.
